name: Build macOS app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # HEIC pour pillow-heif
      - name: Install Homebrew deps
        run: |
          brew update
          brew install libheif

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      # Build via .spec (recommandé), sinon fallback simple
      - name: Build with PyInstaller
        run: |
          if [ -f FaceSorter.spec ]; then
            pyinstaller FaceSorter.spec
          else
            pyinstaller --name "FaceSorter" --windowed --onefile sort_photos_by_person.py
          fi

      - name: Zip app
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "FaceSorter.app" "FaceSorter-macOS.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FaceSorter-macOS
          path: dist/FaceSorter-macOS.zip
