name: Build macOS app (offline)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Homebrew deps (HEIC)
        run: |
          brew update
          brew install libheif

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      # === Option B : télécharger les modèles pendant le build
      # (supprime ce bloc si tu commits déjà insightface_home/ dans le repo)
      - name: Download InsightFace models (buffalo_l)
        run: |
          mkdir -p insightface_home/models/buffalo_l
          curl -L -o buffalo_l.zip "https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip"
          unzip -o buffalo_l.zip -d insightface_home/models/

      - name: Build with PyInstaller (.spec)
        run: |
          pyinstaller FaceSorter.spec

      - name: Zip app
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "FaceSorter.app" "FaceSorter-macOS.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FaceSorter-macOS
          path: dist/FaceSorter-macOS.zip
